name: "Composite Action Test"
description: "Run a simple composite action"
env:
  NAME2: test2
  SERVER: development
inputs:
  your_name:
    description: 'lol'
    default: 'Ethan'
runs:
    using: "composite"
    steps: 
        - run: echo hello ${{inputs.your_name}}
        - run: echo sha ${{github.sha}}
        - run: echo os ${{runner.os}}
        - run: |
            echo job index ${{ strategy.job-index }}
        - run: echo Name2 $NAME2
        - run: echo Server $SERVER
        - run: echo Server changed to $SERVER
          env:
            SERVER: templeos
        - run: echo Composite Action Server $SERVER
        - run: echo Name3 $NAME3
        - run: echo Name3 changed to $NAME3
          env:
            NAME3: fdasdfadsf
