name: "Composite Action Test"
description: "Run a simple composite action"
inputs:
  your_name:
    description: 'lol'
    default: 'Ethan'
# outputs:
#   random_number: ${{ steps.random_number_generator.outputs.random_id }}
#   food: ${{ steps.food.outputs.test }}
runs:
    using: "composite"
    steps: 
      - env:
          bar: this is bar 
        shell: bash
        run: |
          echo '::set-env name=baz::this is baz'
          echo printenv|sort
        
