name: "Composite Action Test"
description: "Run a simple composite action"
inputs:
  your_name:
    description: 'lol'
    default: 'Ethan'
runs:
    env:
      NAME2: test2
      SERVER: development
    using: "composite"
    steps: 
        - run: echo hello ${{inputs.your_name}}
        - run: echo sha ${{github.sha}}
        - run: echo os ${{runner.os}}
        - run: |
            echo job index ${{ strategy.job-index }}
        - name: test composite action env
          run: echo Name2 $NAME2
        - name: test composite action env 2
          run: echo Server $SERVER
