name: "Composite Action Test v2"
description: "Run a simple composite action"
runs:
    using: "composite"
    steps: 
        - run: echo beep
        - run: echo beep boop
        - run: echo beep boop boop
