name: "Composite Action Test"
description: "Run multiple run steps"
inputs:
  your_name:
    description: 'Your name'
    default: 'Ethan'
outputs:
  random_number: 
    description: "Random number"
    value: ${{ steps.random_number_generator.outputs.random_id }}
  food: 
    description: "Food"
    value: ${{ steps.food.outputs.test }}
runs:
    using: "composite"
    steps:
#       - run: echo test before checkout
#         shell: bash
#       - uses: actions/checkout@v2
#       - run: echo test after checkout
#         shell: bash
      - run: echo Hi ${{ inputs.your_name }}
        shell: bash
      - run: echo os ${{runner.os}}
        shell: bash
      - run: echo action step env.foo ${{ env.foo }}
        env: 
          foo: this is foo 2
        shell: bash
#       - uses: actions/checkout@v2
      - id: composite2
        uses: ethanchewy/composite2@v2
        with: 
          favorite_animal: "frog"
