name: "Composite Action Test"
description: "Run multiple run steps"
inputs:
  your_name:
    description: 'Your name'
    default: 'Ethan'
outputs:
  random_number: 
    description: "Random number"
    value: ${{ steps.random_number_generator.outputs.random_id }}
  food: 
    description: "Food"
    value: ${{ steps.food.outputs.test }}
runs:
    using: "composite"
    steps:
      - run: echo Hi ${{ inputs.your_name }}
        shell: bash
      - run: echo os ${{runner.os}}
        shell: bash
      - run: echo action step env.foo ${{ env.foo }}
        env: 
          foo: this is foo 2
        shell: bash
      - run: echo '::set-env name=foo::this is foo 3'
        shell: bash
      - run: echo new env.foo for everything ${{ env.foo }}
        shell: bash
      - id: random_number_generator
        run: echo "::set-output name=random_id::$(echo $RANDOM)"
        shell: bash
      - id: food
        run: echo "::set-output name=test::strawberry"
        shell: bash
      - run: dir
        shell: pwsh
      - run: pwd
        working-directory: test
        shell: bash
